name: focus5
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  # Adjust the SDK constraint based on your Flutter version
  # Use `flutter --version` to check your Flutter version
  sdk: '>=3.0.0 <4.0.0' 
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase (Updated Versions)
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  # Removed firebase_auth_web - handled by firebase_auth
  # Removed firebase_storage_web - handled by firebase_storage

  # State Management
  provider: ^6.0.5 # Consider updating if needed

  # UI/UX
  cupertino_icons: ^1.0.2
  transparent_image: ^2.0.0
  url_launcher: ^6.0.0 # Add url_launcher if not present or update

  # Video
  video_player: ^2.7.0 # Consider updating if needed

  # Storage
  shared_preferences: ^2.2.0 # Consider updating if needed

  # Other utilities
  uuid: ^4.0.0
  path: ^1.8.3 # Consider updating if needed
  flutter_app_badger: ^1.5.0 # This package is discontinued, consider replacement

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Consider updating

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/videos/
    # Add other asset types if needed

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  # ... (dev_dependencies) 