name: focus5
description: "A mental training app for athletes"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core Firebase
  firebase_core: ^2.24.0

  # Authentication
  firebase_auth: ^4.15.0
  google_sign_in: ^6.1.6
  flutter_secure_storage: ^9.0.0

  # UI & State Management
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  glassmorphism: ^3.0.0 # For glass effect
  flutter_staggered_grid_view: ^0.7.0 # For DiscoverScreen grid
  uuid: ^4.2.1
  percent_indicator: ^4.2.3
  transparent_image: ^2.0.1
  flutter_markdown: ^0.6.17
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.5.0
  lottie: ^2.6.0

  # Animations
  flutter_animate: ^4.4.0

  # Media Playback
  just_audio: ^0.9.36
  video_player: ^2.8.6
  chewie: ^1.11.1  # Using Chewie with video_player
  # better_player: ^0.0.83  # Using Better Player instead of Flick
  # flick_video_player: ^0.9.0  # Removing this package
  audioplayers: ^5.2.1 # Added back (check if needed vs just_audio)
  audio_video_progress_bar: ^2.0.3 # Added back

  # Utilities
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  http: ^1.1.0
  flutter_native_splash: ^2.4.0 # For splash screen
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  timeago: ^3.5.0
  image_picker: ^1.0.4
  share_plus: ^7.1.0

  # RevenueCat (Optional - if implementing subscriptions)
  purchases_flutter: ^6.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/logos/
    - assets/audio/
    - assets/videos/
    - assets/icons/
    - assets/images/logo.png
    - assets/images/avatars/coach1.jpg
    - assets/images/avatars/coach2.jpg
    - assets/images/avatars/coach3.jpg
    - assets/images/avatars/user.jpg
    - assets/images/avatars/team.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # Removed fonts section since we don't have the font files
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
