/// List of sports available in the app
final List<String> sports = [
  'American Football',
  'Archery',
  'Athletics',
  'Badminton',
  'Baseball',
  'Basketball',
  'Boxing',
  'Cricket',
  'Cycling',
  'Diving',
  'Equestrian',
  'Fencing',
  'Field Hockey',
  'Figure Skating',
  'Golf',
  'Gymnastics',
  'Handball',
  'Ice Hockey',
  'Judo',
  'Karate',
  'Lacrosse',
  'Martial Arts',
  'Rowing',
  'Rugby',
  'Sailing',
  'Soccer',
  'Softball',
  'Swimming',
  'Table Tennis',
  'Tennis',
  'Triathlon',
  'Volleyball',
  'Weightlifting',
  'Wrestling',
  'Other',
]; 